---
:verbose: true
:concurrency: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
  - ['development.the_comments_jobs', 5]
  - [single, 1]

:limits:
  'development.the_comments_jobs': 5
  single: 1
